tony_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: TonyUserBundle:Default:index }

tony_user_callback:
    path:     /callback
    defaults: { _controller: TonyUserBundle:CallbackHandler:index }

